def f(a,b)

end

begin
f

rescue ArgumentError=> ex
print exception.message
end